/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.productor_consumidor;

/**
 *
 * @author erick
 */
public class PanaderoClienteGUI extends javax.swing.JFrame {
    
private final int capacidadAlmacen = 5;
private final Almacen almacen = new Almacen(capacidadAlmacen, this); // Pasamos la referencia a la GUI
 private Panadero panadero1;
    private Cliente cliente1;
    private Thread hiloPanadero;
    private Thread hiloCliente;
    /**
     * Creates new form PanaderoClienteGUI
     */
    public PanaderoClienteGUI() {
        initComponents();
        
        botonDetenerPanadero.setEnabled(false);
        botonDetenerCliente.setEnabled(false);
        areaTextoContenidoBandeja.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaCapacidadAlmacen = new javax.swing.JLabel();
        etiquetaCantidadPanes = new javax.swing.JLabel();
        etiquetaContenidoBandeja = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextoContenidoBandeja = new javax.swing.JTextArea();
        botonIniciarPanadero = new javax.swing.JButton();
        botonDetenerPanadero = new javax.swing.JButton();
        botonIniciarCliente = new javax.swing.JButton();
        botonDetenerCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaCapacidadAlmacen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiquetaCapacidadAlmacen.setText("Capacidad del Almacen: X");

        etiquetaCantidadPanes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiquetaCantidadPanes.setText("Cantidad de Panes en el Almacén : 0");

        etiquetaContenidoBandeja.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiquetaContenidoBandeja.setText("Contenido de la bandeja:");

        areaTextoContenidoBandeja.setEditable(false);
        areaTextoContenidoBandeja.setColumns(20);
        areaTextoContenidoBandeja.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        areaTextoContenidoBandeja.setRows(5);
        jScrollPane1.setViewportView(areaTextoContenidoBandeja);

        botonIniciarPanadero.setText("Iniciar Panadero");
        botonIniciarPanadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarPanaderoActionPerformed(evt);
            }
        });

        botonDetenerPanadero.setText("Detener Panadero");
        botonDetenerPanadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerPanaderoActionPerformed(evt);
            }
        });

        botonIniciarCliente.setText("Iniciar Cliente");
        botonIniciarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarClienteActionPerformed(evt);
            }
        });

        botonDetenerCliente.setText("Detener Cliente");
        botonDetenerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(botonIniciarPanadero)
                .addGap(74, 74, 74)
                .addComponent(botonDetenerPanadero)
                .addGap(148, 148, 148)
                .addComponent(botonIniciarCliente)
                .addGap(55, 55, 55)
                .addComponent(botonDetenerCliente)
                .addGap(0, 119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiquetaCantidadPanes, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaCapacidadAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaContenidoBandeja, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(261, 261, 261))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(etiquetaCantidadPanes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaContenidoBandeja, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaCapacidadAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIniciarPanadero)
                    .addComponent(botonDetenerPanadero)
                    .addComponent(botonIniciarCliente)
                    .addComponent(botonDetenerCliente))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarPanaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarPanaderoActionPerformed
        iniciarPanadero();
    }//GEN-LAST:event_botonIniciarPanaderoActionPerformed

    private void botonDetenerPanaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerPanaderoActionPerformed
        detenerPanadero();
    }//GEN-LAST:event_botonDetenerPanaderoActionPerformed

    private void botonIniciarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarClienteActionPerformed
        iniciarCliente();
    }//GEN-LAST:event_botonIniciarClienteActionPerformed

    private void botonDetenerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerClienteActionPerformed
       detenerCliente();
    }//GEN-LAST:event_botonDetenerClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanaderoClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanaderoClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanaderoClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanaderoClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanaderoClienteGUI().setVisible(true);
            }
        });
        
    }

    
    private void iniciarPanadero() {
        panadero1 = new Panadero(almacen, 1); // Puedes usar un ID fijo por ahora
        hiloPanadero = new Thread(panadero1);
        hiloPanadero.start();
        botonIniciarPanadero.setEnabled(false);
        botonDetenerPanadero.setEnabled(true);
        actualizarInterfaz(); // Actualizamos la interfaz para mostrar el estado inicial
    }

    private void detenerPanadero() {
        if (panadero1 != null) {
            panadero1.detener();
            hiloPanadero = null; // Podemos liberar la referencia al hilo
        }
        botonIniciarPanadero.setEnabled(true);
        botonDetenerPanadero.setEnabled(false);
    }
    
    private void iniciarCliente() {
        cliente1 = new Cliente(almacen, 1); // Puedes usar un ID fijo por ahora
        hiloCliente = new Thread(cliente1);
        hiloCliente.start();
        botonIniciarCliente.setEnabled(false);
        botonDetenerCliente.setEnabled(true);
        actualizarInterfaz(); // Actualizamos la interfaz para mostrar el estado inicial
    }

    private void detenerCliente() {
        if (cliente1 != null) {
            cliente1.detener();
            hiloCliente = null; // Podemos liberar la referencia al hilo
        }
        botonIniciarCliente.setEnabled(true);
        botonDetenerCliente.setEnabled(false);
    }
    
    
    public void actualizarInterfaz() {
        etiquetaCantidadPanes.setText("Cantidad de Panes en el Almacén: " + almacen.getCantidadPanes());
        areaTextoContenidoBandeja.setText(almacen.getContenidoBandeja() + "\n");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTextoContenidoBandeja;
    private javax.swing.JButton botonDetenerCliente;
    private javax.swing.JButton botonDetenerPanadero;
    private javax.swing.JButton botonIniciarCliente;
    private javax.swing.JButton botonIniciarPanadero;
    private javax.swing.JLabel etiquetaCantidadPanes;
    private javax.swing.JLabel etiquetaCapacidadAlmacen;
    private javax.swing.JLabel etiquetaContenidoBandeja;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
