/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.notashistoria;

/**
 *
 * @author erick
 */

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.Semaphore;


public class Interfaz extends javax.swing.JFrame {
    
    private Semaphore semaforoNarrador;
    private Semaphore semaforoUsuario;
    private DefaultListModel<String> modeloHistoria;
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        modeloHistoria = new DefaultListModel<>();
        
        
        semaforoNarrador = new Semaphore(1);
        semaforoUsuario = new Semaphore(0);
        
        listaHistoria.setModel(modeloHistoria);
    
        Usuario usuario = new Usuario(this, semaforoNarrador, semaforoUsuario, areaResumen);
        usuario.agregarEventos();
        
        usuario.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaHistoria = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaResumen = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonIniciar = new javax.swing.JButton();
        estadoUsuario = new javax.swing.JLabel();
        estadoNarrador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listaHistoria);

        areaResumen.setColumns(20);
        areaResumen.setRows(5);
        jScrollPane2.setViewportView(areaResumen);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Narrador");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Notas");

        botonIniciar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonIniciar.setText("Iniciar");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });

        estadoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estadoUsuario.setText("Usuario: En espera");

        estadoNarrador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estadoNarrador.setText("Narrador: En espera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estadoNarrador, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadoNarrador, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
             List<String> historia = Arrays.asList(
    "En un mundo donde los sistemas operativos dominaban el mundo digital, un grupo de ingenieros visionarios buscaba una alternativa libre y abierta a los sistemas cerrados que dominaban el mercado, lo que llevó a un joven programador llamado Linus Torvalds a crear el núcleo de un nuevo sistema operativo llamado Linux.",
    "La historia comenzó a finales de los años 80, cuando Linus, entonces estudiante en la Universidad de Helsinki, decidió desarrollar su propio sistema operativo que fuera accesible para todos, sin las restricciones impuestas por los sistemas comerciales. Comenzó como un proyecto pequeño, pero rápidamente creció cuando otros programadores de todo el mundo se unieron a él para contribuir al proyecto.",
    "A medida que el sistema operativo Linux fue evolucionando, empezó a ganar popularidad entre los entusiastas de la informática, quienes apreciaban la libertad que ofrecía para personalizar y modificar el sistema según sus necesidades. Esto, junto con su estabilidad y seguridad, hizo que Linux fuera cada vez más utilizado en servidores y supercomputadoras, un campo donde dominaba hasta el momento otro gigante.",
    "A lo largo de los años, el ecosistema Linux creció con miles de distribuciones (conocidas como 'distros') que ofrecían diversas versiones del sistema, adaptadas a todo tipo de usuarios: desde aquellos que necesitaban un sistema ligero hasta los que requerían un entorno empresarial robusto. Distros como Ubuntu, Fedora y Debian ganaron tracción entre los usuarios de escritorio, mientras que CentOS y Red Hat se convirtieron en los sistemas operativos preferidos para servidores empresariales.",
    "Pero no todo fue fácil. A pesar de su popularidad en servidores, Linux tuvo que luchar por un lugar en el escritorio personal. Las interfaces gráficas de usuario (GUI) como GNOME, KDE y más tarde Xfce mejoraron la experiencia del usuario, pero la mayoría de las personas seguían utilizando Windows o macOS debido a la falta de soporte de aplicaciones y la resistencia al cambio.",
    "Con el tiempo, Linux y su comunidad crecieron en número y poder. La colaboración de miles de programadores, los avances en las herramientas de desarrollo y el crecimiento de plataformas como GitHub hicieron que el sistema operativo libre fuera cada vez más accesible y amigable para nuevos usuarios. Los gigantes de la tecnología comenzaron a darse cuenta de su potencial.",
    "En la última década, Linux ha tenido un resurgimiento impresionante. Empresas como Google adoptaron Linux para Android, el sistema operativo más utilizado en teléfonos móviles del mundo. Grandes empresas de tecnología, como Facebook, Amazon y Microsoft, comenzaron a integrar soluciones basadas en Linux para sus infraestructuras tecnológicas. Incluso Microsoft, históricamente un rival, comenzó a adoptar Linux a través de su propia plataforma y servicios como Azure.",
    "Hoy en día, Linux no solo es utilizado por programadores y administradores de sistemas, sino que se ha convertido en la base de muchas de las tecnologías que impulsan el mundo moderno. Desde la nube hasta dispositivos de Internet de las Cosas (IoT), Linux ha demostrado que un sistema operativo abierto y libre puede no solo competir, sino también sobresalir en el panorama digital."
);


        botonIniciar.setEnabled(false);

       new Narrador(modeloHistoria, historia, this, semaforoNarrador, semaforoUsuario).start();
    }//GEN-LAST:event_botonIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    


    public void bloquearUsuario(boolean bloquear) {
        areaResumen.setEditable(!bloquear); 
    }

    public void actualizarEstado(String estadoN, String estadoU) {
        estadoNarrador.setText("Narrador: " + estadoN);
        estadoUsuario.setText("Usuario: " + estadoU);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResumen;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JLabel estadoNarrador;
    private javax.swing.JLabel estadoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaHistoria;
    // End of variables declaration//GEN-END:variables
}
